name: build
on: [push, pull_request]

jobs:
  test:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.3

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Test
        run: poetry run pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Lint
        run: |
          poetry run pylint **/*.py --errors-only
          poetry run black **/*.py --check

      - uses: jakebailey/pyright-action@v1
